info:
  artifactId: '${project.name}'
  version: '${project.version}'

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/m2m_product?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
     ddl-auto: validate

